/**
 * orders/import 에러 코드 공통 상수
 * - 서버(route, service)와 테스트가 동일 코드를 참조하도록 함
 */
export const ORDER_IMPORT_ERROR_CODES = {
  MISSING_REQUIRED: 'MISSING_REQUIRED',
  ORDER_NO_TOO_LONG: 'ORDER_NO_TOO_LONG',
  RECV_NAME_TOO_LONG: 'RECV_NAME_TOO_LONG',
  INVALID_PHONE: 'INVALID_PHONE',
  ADDRESS_TOO_LONG: 'ADDRESS_TOO_LONG',
  ZIP_TOO_LONG: 'ZIP_TOO_LONG',
  PRODUCT_NAME_TOO_LONG: 'PRODUCT_NAME_TOO_LONG',
  DUPLICATE_ORDER_NO: 'DUPLICATE_ORDER_NO',
  EXTERNAL_SYNC_FAILED: 'EXTERNAL_SYNC_FAILED',
  IMPORT_ROW_ERROR: 'IMPORT_ROW_ERROR',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const;

export type OrderImportErrorCode =
  (typeof ORDER_IMPORT_ERROR_CODES)[keyof typeof ORDER_IMPORT_ERROR_CODES];
